# Generated by Django 3.0rc1 on 2019-11-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('observacoes', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Disponível'), (2, 'Indisponível')], max_length=1)),
            ],
        ),
    ]
