# Generated by Django 3.0rc1 on 2019-11-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='status',
            field=models.IntegerField(choices=[(1, 'Disponível'), (2, 'Indisponível')]),
        ),
    ]
